# Dockerfile para Node.js Alpine 20
FROM node:20-alpine

WORKDIR /app

# Instala git para clonar o repositório
RUN apk add --no-cache git

# Clona o repositório público do GitHub
RUN git clone https://github.com/igorsacramento/bot-wiki .

# Instala dependências
RUN npm install

# Copia o entrypoint
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

EXPOSE 3000

CMD ["/bin/sh", "/app/entrypoint.sh"]
